### DISCUSSION TITLE
Help! Installing on my NAS

### DISCUSSION THREAD

**Discussion by Jcruzi** [itsToggle/plex_debrid#387] [Q&A]
Hello Legends!

I am confused and do not know how to proceed on installing this on my Synology NAS runing on DSM 7.1

Your help will be greatly appreciated.

Cheers!

**Comment by ph1signals** [comment]
Hello, can you install docker on it?

**Reply by Jcruzi** [reply]
Yes! I do have docker installed.

**Reply by itsToggle** [reply]
there are also some NAS guides available on the plex_debrid discord server :)

**Reply by itsToggle** [reply]
https://discord.com/channels/1021692389368283158/1069137865470136330

**Reply by Jcruzi** [reply]
For sure reason i can't access the discord server

**Reply by raynoxfr** [reply]
If you don't want to take a lot of time, I have made a YAML for Docker :
And you can use the interactive mode in Portainer (Web interface to manage the docker image / container) with "attach" button... to configure it :

```
  version: '2'
  services:
    rclone:
        container_name: plex_debrid
        image: itstoggle/plex_debrid:latest
        restart: unless-stopped
        volumes:
            - /path:/config
        network_mode: bridge
        environment:
          - PUID=0
          - PGID=0
          - TZ=Europe/Paris
        stdin_open: true # docker run -i
        tty: true        # docker run -t

```
